gantt
    title Biblioteca Digital v1.0 - Cronograma de Desarrollo
    dateFormat  YYYY-MM-DD
    axisFormat  %d/%m

    section Gestión
    A1 — Plan de proyecto          :done,    a1, 2026-06-01, 1d
    A2 — Registro de riesgos       :done,    a2, 2026-06-02, 1d

    section Diseño y Arquitectura
    A3 — Diseñar ERD               :done,    a3, 2026-06-02, 1d
    A4 — Esquema BD (DDL)          :done,    a4, 2026-06-03, 1d
    A5 — Swagger / OpenAPI         :done,    a5, 2026-06-03, 2d
    A6 — Diagrama C4               :active,  a6, 2026-06-05, 1d

    section Desarrollo
    A7 — CRUD de libros            :         a7, 2026-06-05, 2d
    A8 — Validador ISBN-13         :         a8, 2026-06-07, 1d
    A9 — Autenticación             :         a9, 2026-06-05, 2d
    A10 — Gestión de lectores      :         a10, 2026-06-07, 1d
    A11 — Lógica disponibilidad    :         a11, 2026-06-07, 1d
    A12 — Flujo préstamo/dev.      :         a12, 2026-06-08, 2d
    A13 — Notificaciones email     :         a13, 2026-06-10, 1d

    section Calidad
    A14 — Pruebas unitarias         :         a14, 2026-06-11, 1d
    A15 — UAT con usuarios          :         a15, 2026-06-12, 1d

    section Despliegue y Cierre
    A16 — Infraestructura           :         a16, 2026-06-13, 1d
    A17 — Documentación técnica     :         a17, 2026-06-14, 1d
    A18 — Handover a operaciones    :         a18, 2026-06-15, 1d
    A19 — Cierre del proyecto       :         a19, 2026-06-16, 1d
